### PR TITLE
Fix negative signal output

### LINKED ISSUE #4: Check gives critical value because of negative dbm count (?)
Hi I just checked the plugin and it gives a critical value because (I think) the dbm is shown in a negative value:

Braintower FW version: 3.5.4
 
./check_braintower -H host --ssl-insecure
check_braintower: CRITICAL - que: 0 failed: 0 signal: -69 db total: 7 state: SIGNAL_OK load: 0.02;0.02;0.05 time: 1538133709 disk free: 25885097984 uptime: 17 min,   0 users|'failed'=0 'signal'=-69 'total'=7 'que'=0

Controlcheck:
./check_braintower -H host --ssl-insecure -Q 1 -F 1
check_braintower: CRITICAL - que: 0 failed: 0 signal: -67 db total: 7 state: SIGNAL_OK load: 0.01;0.02;0.05 time: 1538133740 disk free: 25885102080 uptime: 18 min,   0 users|'failed'=0 'signal'=-67 'total'=7 'que'=0

./check_braintower -H host --ssl-insecure --signal-warning 0 --signal-critical 0
check_braintower: CRITICAL - que: 0 failed: 0 signal: -67 db total: 7 state: SIGNAL_OK load: 0.01;0.02;0.05 time: 1538133786 disk free: 25885102080 uptime: 19 min,   0 users|'failed'=0 'signal'=-67 'total'=7 'que'=0

./check_braintower -H host --ssl-insecure --signal-warning -80 --signal-critical -80
check_braintower: OK - que: 0 failed: 0 signal: -67 db total: 7 state: SIGNAL_OK load: 0;0.01;0.05 time: 1538133812 disk free: 25885102080 uptime: 19 min,   0 users|'failed'=0 'signal'=-67 'total'=7 'que'=0

Looks likt the diff is done in a wrong direction?

### PR DESCRIPTION
**Pull request by MarcusCaepio**
replace the "-" of the signal output to have correct alarms for --signal-warning and --signal-critical

Fixes #4

### CODE REVIEW

**Comment by MarcusCaepio** [comment]
Control:
./check_braintower -H host --ssl-insecure -Q 1 -F 1 --signal-warning 50 --signal-critical 0
check_braintower: OK - que: 0 failed: 0 signal: -67 db total: 7 state: SIGNAL_OK load: 0;0.03;0.05 time: 1538135184 disk free: 25885052928 uptime: 42 min,   0 users|'failed'=0 'signal'=67 'total'=7 'que'=0

**Comment by MarcusCaepio** [comment]
I want to cancel this pull request. I had a fallacy about the dbm measurement. The lower the value, the worse is the signal. But in this case the default threshold of 0 makes no sense :)

**Comment by mxhash** [comment]
Okay understand. But still thank you for the PR!

**Comment by MarcusCaepio** [comment]
Maybe you want to assign the default thresholds for the signal warn and crit based on the braintower docs? https://docs.braintower.de/display/SMSGWDOC/Signal+strength+and+modem+status. I set warning to -91 and critical to -101 in my setup.

**Pull request closed without merging**
