### PR TITLE
Be nice and add a file suffix to the program

### PR DESCRIPTION
**Pull request by RincewindsHat**

### CODE REVIEW

**Review by martialblog — CHANGES_REQUESTED** [review]
Also requires an update to the README. Otherwise :+1:

**Comment by pdorschner** [comment]
It's not really necessary to add the file suffix, because of the shebang `!/usr/bin/env python`. More over, it could happen, that some users may run into issues due to renaming of the check plugin.

**Comment by martialblog** [comment]
Many other (Python based) check do not have a suffix. I vote we close this.

**Comment by lbetz** [comment]
Because there is much without, but still does not do well. I find a suffix very helpful ... and many others have one. On the other hand, this would only work with a v3.x release.

**Comment by martialblog** [comment]
We'll keep it the way it is for now, for backwards compatability reasons

**Pull request closed without merging**
